### ISSUE TITLE
Install Sentry

### ISSUE THREAD

**Issue by jovv** [jovv/SEBC#13]

**Comment by jovv** [comment]
Installed and configured Sentry but ran out of time for the beeline/beeswax instructions.
Added a screenshot of the Cloudera Manager Home: 6_sentry_installed_and_configured.PNG

**Comment by mfernest** [comment]
I'd almost like to mark this complete to show my appreciate for the previous work. Your submissions are clean, accurate, easy to read. It's a pleasure and a breeze to evaluate work of this quality.
