### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by jovv** [jovv/SEBC#2]

**Comment by jovv** [comment]
Finished replication to another cluster.

**Comment by jovv** [comment]
Finished Test HDFS throughput

**Comment by jovv** [comment]
Finished Test HDFS Snapshots

**Comment by jovv** [comment]
Cloudera Manager URL:
http://ec2-54-229-221-110.eu-west-1.compute.amazonaws.com:7180/cmf/home

**Comment by jovv** [comment]
Would prefer not to post the CM URL as this is a public repo. Thanks for understanding.

**Comment by cfusi** [comment]
That's OK
